---
language: go

go:
  - 1.11.4

env:
  - GO111MODULE=on

services:
  - docker
before_install:
  - sudo service mysql stop || sudo service mysql-5.6 stop || sudo stop mysql-5.6 || sudo stop mysql || echo "failed to stop mysql"
  - hack/mysqld.sh

install: make deps
script: make migrate_test all

notifications:
    email: false
