version: "3.7"

services:

  gothic:
    image: gothic:latest
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ${ENV_FILE:-./env/sim.env}
    expose:
      - "7720"
      - "7721"
      - "7722"
      - "7727"
      - "7729"
    ports:
      - "7720:7720"
      - "7721:7721"
      - "7722:7722"
      - "7727:7727"
      - "7729:7729"
    restart: unless-stopped

  envoy:
    image: envoyproxy/envoy:v1.21-latest
    command: /usr/local/bin/envoy -c /etc/envoy/envoy.yaml ${ENVOY_FLAGS:-}
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    expose:
      - "8080"
      - "9901"
    ports:
      - "8001:8080"
      - "9901:9901"
    restart: unless-stopped
    # make this work on linux
    # extra_hosts:
    #  host.docker.internal: 172.17.0.1
