version: "3.8"

services:

  mysql:
    image: mysql:latest
    command: --init-file /data/application/init.sql
    volumes:
      - ./dev.sql:/data/application/init.sql
      - db_volume:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - CLIENT_MULTI_STATEMENTS=true
    expose:
      - '3306'
    ports:
      - "3306:3306"
    #https://stackoverflow.com/questions/55559386/how-to-fix-mbind-operation-not-permitted-in-mysql-error-log
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE

  pg:
    image: postgres:latest
    volumes:
      - db_volume:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - PGDATA=var/lib/postgresql/data/db/
    expose:
      - '5432'
    ports:
      - "5432:5432"

volumes:
  db_volume: { }
