package key

// Key is a key
type Key string

const (
	// Unknown key
	Unknown Key = ""
	// AccountID key
	AccountID = "account_id"
	// Action key
	Action = "action"
	// AdminID key
	AdminID = "admin_id"
	// AvatarURL key
	AvatarURL = "avatar_url"
	// Class key
	Class = "class"
	// Code key
	Code = "code"
	// ConfirmedAt key
	ConfirmedAt = "confirmed_at"
	// Color key
	Color = "color"
	// Data key
	Data = "data"
	// Description key
	Description = "description"
	// Email key
	Email = "email"
	// Event key
	Event = "event"
	// ExpirationDate key
	ExpirationDate = "expiration_date"
	// Fields key
	Fields = "fields"
	// Filters key
	Filters = "filters"
	// FirstName key
	FirstName = "first_name"
	// Hostname key
	Hostname = "hostname"
	// ID key
	ID = "id"
	// IPAddress key
	IPAddress = "ip_address"
	// Issued key
	Issued = "issued"
	// JWT key
	JWT = "jwt"
	// LastName key
	LastName = "last_name"
	// LastUsed key
	LastUsed = "last_used"
	// Logger key
	Logger = "logger"
	// Name key
	Name = "name"
	// Nickname key
	Nickname = "nickname"
	// Page key
	Page = "page"
	// PageCount key
	PageCount = "page_count"
	// Password key
	Password = "password"
	// PerPage key
	PerPage = "per_page"
	// Provider key
	Provider = "provider"
	// ReCaptcha key
	ReCaptcha = "recaptcha"
	// Revoked key
	Revoked = "revoked"
	// Role key
	Role = "role"
	// Service key
	Service = "service"
	// Session key
	Session = "session"
	// Sort key
	Sort = "sort"
	// State key
	State = "state"
	// Status key
	Status = "status"
	// Timestamp key
	Timestamp = "timestamp"
	// Token key
	Token = "token"
	// Type key
	Type = "type"
	// Usage key
	Usage = "usage"
	// UserID key
	UserID = "user_id"
	// Username key
	Username = "username"
)
