// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package signup

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SignupClient is the client API for Signup service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SignupClient interface {
	CreateSignupCodes(ctx context.Context, in *CreateSignupCodesRequest, opts ...grpc.CallOption) (*CreateSignupCodesResponse, error)
	CheckSignupCode(ctx context.Context, in *CheckSignupCodeRequest, opts ...grpc.CallOption) (*CheckSignupCodeResponse, error)
	VoidSignupCode(ctx context.Context, in *VoidSignupCodeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type signupClient struct {
	cc grpc.ClientConnInterface
}

func NewSignupClient(cc grpc.ClientConnInterface) SignupClient {
	return &signupClient{cc}
}

func (c *signupClient) CreateSignupCodes(ctx context.Context, in *CreateSignupCodesRequest, opts ...grpc.CallOption) (*CreateSignupCodesResponse, error) {
	out := new(CreateSignupCodesResponse)
	err := c.cc.Invoke(ctx, "/signup.Signup/CreateSignupCodes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *signupClient) CheckSignupCode(ctx context.Context, in *CheckSignupCodeRequest, opts ...grpc.CallOption) (*CheckSignupCodeResponse, error) {
	out := new(CheckSignupCodeResponse)
	err := c.cc.Invoke(ctx, "/signup.Signup/CheckSignupCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *signupClient) VoidSignupCode(ctx context.Context, in *VoidSignupCodeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/signup.Signup/VoidSignupCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SignupServer is the server API for Signup service.
// All implementations must embed UnimplementedSignupServer
// for forward compatibility
type SignupServer interface {
	CreateSignupCodes(context.Context, *CreateSignupCodesRequest) (*CreateSignupCodesResponse, error)
	CheckSignupCode(context.Context, *CheckSignupCodeRequest) (*CheckSignupCodeResponse, error)
	VoidSignupCode(context.Context, *VoidSignupCodeRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedSignupServer()
}

// UnimplementedSignupServer must be embedded to have forward compatible implementations.
type UnimplementedSignupServer struct {
}

func (UnimplementedSignupServer) CreateSignupCodes(context.Context, *CreateSignupCodesRequest) (*CreateSignupCodesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSignupCodes not implemented")
}
func (UnimplementedSignupServer) CheckSignupCode(context.Context, *CheckSignupCodeRequest) (*CheckSignupCodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckSignupCode not implemented")
}
func (UnimplementedSignupServer) VoidSignupCode(context.Context, *VoidSignupCodeRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VoidSignupCode not implemented")
}
func (UnimplementedSignupServer) mustEmbedUnimplementedSignupServer() {}

// UnsafeSignupServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SignupServer will
// result in compilation errors.
type UnsafeSignupServer interface {
	mustEmbedUnimplementedSignupServer()
}

func RegisterSignupServer(s grpc.ServiceRegistrar, srv SignupServer) {
	s.RegisterService(&Signup_ServiceDesc, srv)
}

func _Signup_CreateSignupCodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSignupCodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SignupServer).CreateSignupCodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/signup.Signup/CreateSignupCodes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SignupServer).CreateSignupCodes(ctx, req.(*CreateSignupCodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Signup_CheckSignupCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckSignupCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SignupServer).CheckSignupCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/signup.Signup/CheckSignupCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SignupServer).CheckSignupCode(ctx, req.(*CheckSignupCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Signup_VoidSignupCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VoidSignupCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SignupServer).VoidSignupCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/signup.Signup/VoidSignupCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SignupServer).VoidSignupCode(ctx, req.(*VoidSignupCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Signup_ServiceDesc is the grpc.ServiceDesc for Signup service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Signup_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "signup.Signup",
	HandlerType: (*SignupServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSignupCodes",
			Handler:    _Signup_CreateSignupCodes_Handler,
		},
		{
			MethodName: "CheckSignupCode",
			Handler:    _Signup_CheckSignupCode_Handler,
		},
		{
			MethodName: "VoidSignupCode",
			Handler:    _Signup_VoidSignupCode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "signup.proto",
}
