name: Dependency License Scanning

on:
  push:
    branches:
      - master

defaults:
  run:
    shell: bash

jobs:
  fossa-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Dependencies
        uses: actions/checkout@v2
      - name: Fossa
        uses: fossas/fossa-action@v1
        with:
         api-key: ${{secrets.FOSSA_API_KEY}}
