on:
  push:
  pull_request:
    types: [ opened, synchronize, reopened ]
name: test
jobs:
  test:
    strategy:
      matrix:
        go-version: [ 1.15.x, 1.16.x ]
    runs-on: ubuntu-latest
    steps:
      #- name: Install workflow dependencies
      #  run: apt update && apt install -y make gcc
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: make deps
      - name: Lint and test
        run:  make all COVERAGE=1
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1

